spring:
  application:
    name: todo
  jpa:
    hibernate:
      ddl-auto: validate
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:todo_db
    username: admin
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000  # 10 minutes
      connection-timeout: 30000  # 30 seconds
      max-lifetime: 1800000  # 30 minutes
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 10000
  shutdown: graceful

security:
  jwt:
    secret: secret
    expiration-time: 3600000 # 1 hour
  user:
    full-name: Admin
    email: admin@email.com
    password: pass
